# Generated by Django 3.2 on 2023-02-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_news_migration'),
        ('mainapp', '0003_courses'),
    ]

    operations = [
    ]
